const config = {
    GOOGLE_MAPS_API_KEY: 'YOUR_GOOGLE_MAPS_API_KEY',
    ONE_BUS_AWAY_API_KEY: 'YOUR_ONE_BUS_AWAY_API_KEY',
    UPDATE_INTERVAL: 60000, // 60 seconds
    MAP_CENTER: { lat: 47.6276, lng: -122.2275 }, // Medina, WA
    MAP_ZOOM: 13
}; 